### ISSUE TITLE
Add cocina.json to BagVerifier

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3496]
`data/metadata/cocina.json` is one of the files that should be verified by Preserve::BagVerifier.

**Comment by edsu** [comment]
@justinlittman I saw the existing tests in [spec/services/preserve/](https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/preserve/bag_verifier_spec.rb) don't exercise `BagVerifier#verify` and that there doesn't seem to be a a Bag in `spec/fixtures`. Should there be a test of `BagVerifier#verify` for this task? Or is that being tested somewhere else?

**Comment by justinlittman** [comment]
Probably a good thing to have a test for. However, to see if covered by an existing test, break it and then run all of the tests.

**Comment by edsu** [comment]
Oh good call, I did a

`rm spec/fixtures/workspace/dd/116/zh/0343/dd116zh0343/metadata/cocina.json`

and I did get a couple failures

```
Failures:

  1) SdrIngestService.transfer with no change in content
     Failure/Error: raise "#{pathname.basename} not found at #{pathname}" unless pathname.exist?

     RuntimeError:
       cocina.json not found at /Users/edsummers/Projects/sul-dlss/dor-services-app/spec/fixtures/export/dd116zh0343/data/metadata/cocina.json
     # ./app/services/preserve/bag_verifier.rb:42:in `verify_pathname'
     # ./app/services/preserve/bag_verifier.rb:34:in `block in verify'
     # ./app/services/preserve/bag_verifier.rb:33:in `each'
     # ./app/services/preserve/bag_verifier.rb:33:in `verify'
     # ./app/services/preserve/bag_verifier.rb:22:in `verify'
     # ./app/services/sdr_ingest_service.rb:41:in `transfer'
     # ./spec/services/sdr_ingest_service_spec.rb:86:in `block (3 levels) in <top (required)>'

  2) SdrIngestService.transfer with content changes
     Failure/Error: raise "#{pathname.basename} not found at #{pathname}" unless pathname.exist?

     RuntimeError:
       cocina.json not found at /Users/edsummers/Projects/sul-dlss/dor-services-app/spec/fixtures/export/dd116zh0343/data/metadata/cocina.json
     # ./app/services/preserve/bag_verifier.rb:42:in `verify_pathname'
     # ./app/services/preserve/bag_verifier.rb:34:in `block in verify'
     # ./app/services/preserve/bag_verifier.rb:33:in `each'
     # ./app/services/preserve/bag_verifier.rb:33:in `verify'
     # ./app/services/preserve/bag_verifier.rb:22:in `verify'
     # ./app/services/sdr_ingest_service.rb:41:in `transfer'
     # ./spec/services/sdr_ingest_service_spec.rb:50:in `block (3 levels) in <top (required)>'
```

I'll add a note and remove the tests/fixtures.
